name: Run ETL Pipeline

on:
    push:
        branches: [main]
    schedule:
        - cron: '0 * * * *'

jobs:
    run-etl:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            
            - name: Install dependencies
              run: |
                pip install -r requirements.txt
            
            - name: Decode GCP credentials
              run: |
                echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > gcp-key.json
              env:
                GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace}}/gcp-key.json
            
            - name: Run ETL
              run: python etl_pipeline.py
              env:
                WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
                BIGQUERY_TABLE: ${{ secrets.BIGQUERY_TABLE}}
                GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
              